[package]
name = "crc-profile-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"]}
serde_json = "1.0.120"
serde_path_to_error = "0.1.16"
dirs = "5.0.1"
